---
csi:
  enable: false

ingress:
  enabled: true
  hosts:
  - name: storageos.local
    tls: true
    tlsSecret: storageos.local-tls
  secrets:
  - name: storageos.local-tls
    key: dGxza2V5Cg==
    certificate: Y2VydGlmaWNhdGUK

podSecurityPolicy:
  enabled: true

storageclass:
  name: fast2
