---
csi:
  enable: true
  provisionCreds:
    enable: true
    username: username1
    password: password1
    secretName: storageos-provision-creds
  controllerPublishCreds:
    enable: true
    username: username2
    password: password2
    secretName: storageos-ctrl-publish-creds
  nodeStageCreds:
    enable: true
    username: username3
    password: password3
    secretName: storageos-node-stage-creds
  nodePublishCreds:
    enable: true
    username: username4
    password: password4
    secretName: storageos-node-publish-creds

# kvBackend:
#   address: 127.0.0.1:2399
#   backend: etcd

podSecurityPolicy:
  enabled: true

storageclass:
  name: fast1
